frames = [
    "(>        <   )",
    ") >      <    ]",
    "]  >   #<     ]",
    "(   >  @> >   ]",
    "[    >   >    ]",
    "[     >#  >   ]",
    "[   < <@   >  ]",
    "[    <      > ]",
    "[   <        >]",
    "[  <         <)",
    "[ <         < (",
    "[<         <  [",
]

Alias = {
    "atm": "🏧",
    "airport": "🛫",
    "bank": "🏦",
    "bus adda": "🚏",
    "bus stand": "🚏",
    "cinema hall": "🍿",
    "court": "⚖️",
    "currency chest": "💵",
    "escalator": "🛝",
    "fire station": "🚒",
    "food / restaurant": "🍱 ",
    "gate no.": "⛩️",
    "government office": "🏛️",
    "hospital": "🏥",
    "hotels": "🏨",
    "inside": "🏠",
    "kiosk": "🏪",
    "lift": "🛗",
    "locality": "🏘️",
    "locker": "🔒",
    "lounge/party hall": "🎉",
    "mall": "🛒",
    "market": "🛍️",
    "medical/health": "💉",
    "other public service": "🏢",
    "outside": "⛺",
    "pl": "🚉",
    "parking": "🅿️",
    "police booth": "🚓",
    "police station": "👮",
    "porter service": "🧳",
    "railway station": "🚞",
    "religious place": "⛪",
    "restaurant": "🍴",
    "school": "🚸",
    "shop/office": "🏬",
    "stadium / sport": "🏟️",
    "toilet": "🚻",
    "token/automatic vending machine": "🎫",
    "tourist place": "🗽",
    "travel": "🚕",
    "travelator": "🛼",
    "university/college": "🎓",
    "water": "💧",
}
